server:
  port: 8084

feign:
  okhttp:
    enabled: true

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
  db:
    database: hm-user

  swagger:
    package: com.heima.user.controller
